### ISSUE TITLE
Implement a more sophisticated mechanism for calibration checks

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/MagmaSatPlus#50] opened 2020-05-21 15:18 UTC
At the moment the calibration checks are 'hard coded' for each model, there's no reporting for the user anywhere of what the calibration limits are. This also means that the warnings will only tell you that you are outside a calibration range, but won't specify what it is... 

e.g. the warning code produces this warning:
"Pressure is outside the calibration range of the CO2 Fugacity Model. Temperature is outside the calibration range of the CO2 Fugacity Model. Pressure is outside the calibration range of the H2O Fugacity Model. Temperature is outside the calibration range of the H2O Fugacity Model. "

This can be fixed by creating some kind of structure for storing the calibration limits, and then making the code check these. This will (potentially) limit the complexity of the possible checks, but will be much more useful for the user!

**Comment by kaylai** [comment] 2020-05-21 21:21
Agreed. I think a get_calibration_range() method might be useful for every model as well. We can simply print out a statement about what the calibration range is for a passed model, so that the user can easily access this without looking through the documentation.

**Comment by kaylai** [comment] 2020-05-21 21:23
I feel like this duplicates #40 so will merge them.
Duplicate of #40

**Closed by kaylai** 2020-05-21 21:23 UTC
Labels: enhancement
